update the RBAC statement
Shouqianba-FT/elastic-env-operator pull request #16
Opened 2024-08-19 10:09 UTC by runkecheng

fix #15 

为保持原有权限不被误缩小, 保持原角色不变, 
注解生成的角色和原角色都绑定到同一个sa

2024-08-19 10:39 UTC, lujiajing1126 commented
应该需要publish到release的文件吧？

2024-08-20 07:51 UTC, lujiajing1126 commented
![image](https://github.com/user-attachments/assets/6852d400-3242-428c-9678-d77e92f74096)

新上传的deploy文件不是一个合法的YAML

2024-08-20 13:38 UTC, lujiajing1126 requested changes
我们这次会生成一套新的SA和对应的权限是吗？

2024-08-20 13:38 UTC, lujiajing1126 commented on config/manager/manager.yaml
> +      serviceAccountName: elastic-env-operator-manager
你在这里改成了elastic-env-operator-manager，但rbac生成的文件还是叫做manager

2024-08-20 13:38 UTC, lujiajing1126 commented on config/rbac/auth_proxy_role_binding.yaml
>    namespace: system
生成的namespace也是system，应该改成elastic-env-operator-system吧？

2024-08-20 13:38 UTC, lujiajing1126 commented on config/rbac/role.yaml
>    name: manager-role
ClusterRole叫这个名字会和其他Operator生成的冲突的

2024-08-20 13:41 UTC, runkecheng commented on config/manager/manager.yaml
> +      serviceAccountName: elastic-env-operator-manager
单独生成rbac没有应用default里的前缀, 这点确实会不一致

2024-08-20 13:41 UTC, runkecheng commented on config/manager/manager.yaml
> +      serviceAccountName: elastic-env-operator-manager
单独生成rbac没有应用default里的前缀, 这点确实会不一致

2024-08-20 13:42 UTC, lujiajing1126 commented on config/manager/manager.yaml
> +      serviceAccountName: elastic-env-operator-manager
> 单独生成rbac没有应用default里的前缀, 这点确实会不一致

对的。默认是在kustomize文件里面声明的ns变更

2024-08-20 13:56 UTC, runkecheng commented on config/manager/manager.yaml
> +      serviceAccountName: elastic-env-operator-manager
> > 单独生成rbac没有应用default里的前缀, 这点确实会不一致
> 
> 对的。默认是在kustomize文件里面声明的ns变更和统一资源前缀

维护一个用于release的kustomization.yaml, 感觉会更友好一点 
```
# config/release-rbac/kustomization.yaml
namespace: elastic-env-operator-system
namePrefix: elastic-env-operator-
bases:
- ../rbac
```

2024-08-22 01:49 UTC, lujiajing1126 approved these changes

2024-08-22 01:49 UTC, merged